window.__ezLiveIntent=window.__ezLiveIntent||{};Object.assign(window.__ezLiveIntent,{initialized:false,reporting_key:"li-module-enabled",splitPercentage:0.90,moduleEnabled:false,init:async function(){if(this.initialized){return;}
await this.isIdentityFound();const uuid=window._ezaq?.['visit_uuid'];const country=window._ezaq?.country;const bucket=this.getIdentityBridgingExperimentBucket(uuid,country);if(bucket!=='liveintent'){this.initialized=true;return;}
this.determineModuleEnabled();if(this.moduleEnabled){this.addIdentityConfig();this.sendCustomPageviewEvent("li_module_enabled",'true');}else{this.sendCustomPageviewEvent("li_module_enabled",'false');}
this.setTargeting();this.setupEventListeners();this.initialized=true;},isIdentityFound:async function(){while(typeof window.ezoicIdentity==='undefined'||typeof window.ezoicIdentity.getUID!=='function'||typeof window.ezoicIdentity.isInternalUIDSource!=='function'){await new Promise(resolve=>setTimeout(resolve,100));}
return true;},sendInternalTrackingForImpression:function(adUnitGroupId,eidsData){const enriched=Array.isArray(eidsData)&&eidsData.some(item=>item.source==='liveintent.com'||item.provider==='liveintent.com');let targeting=this.moduleEnabled?"t1":"t0";targeting+=enriched?"-e1":"-e0";window.ezoicEvent=window.ezoicEvent||{};window.ezoicEvent.queue=window.ezoicEvent.queue||[];window.ezoicEvent.queue.push(function(){if(window.__ez&&window.__ez.ce&&typeof __ez.ce.AddImpressionEvent==='function'){__ez.ce.AddImpressionEvent(adUnitGroupId,"liveintent_tracking",targeting);}});},getCookie:function(name){const nameEQ=name+"=";const ca=document.cookie.split(';');for(let i=0;i<ca.length;i++){let c=ca[i].trim();if(c.indexOf(nameEQ)===0){return c.substring(nameEQ.length,c.length);}}
return null;},determineModuleEnabled:function(){const cookieName="_ezli_enabled";const cookieExpireDays=30;let cookieValue=this.getCookie(cookieName);if(cookieValue!==null){this.moduleEnabled=cookieValue==="true";}else{this.moduleEnabled=Math.random()<this.splitPercentage;let date=new Date();date.setTime(date.getTime()+(cookieExpireDays*24*60*60*1000));let expires="expires="+date.toUTCString();document.cookie=cookieName+"="+this.moduleEnabled+";"+expires+";path=/";}
window.liModuleEnabled=this.moduleEnabled;},setupEventListeners:function(){window.epbjs=window.epbjs||{};window.epbjs.que=window.epbjs.que||[];epbjs.que.push(()=>{epbjs.onEvent("auctionInit",function(args){let enrichedAuction=args.adUnits&&args.adUnits.some((au)=>au.bids&&au.bids.some((b)=>b.userIdAsEids&&b.userIdAsEids.some((eid)=>eid.source==="liveintent.com"||(eid.uids&&eid.uids.some((uid)=>uid.ext&&uid.ext.provider==="liveintent.com")))));window.__ezLiveIntent.setTargeting(enrichedAuction);});});},setTargeting:function(enriched){let targeting=this.moduleEnabled?"t1":"t0";if(enriched!==undefined)targeting+=enriched?"-e1":"-e0";window.googletag=window.googletag||{cmd:[]};window.googletag.cmd.push(()=>{window.googletag.pubads().setTargeting(this.reporting_key,targeting);});},addIdentityConfig:function(){window.epbjs=window.epbjs||{};window.epbjs.cmd=window.epbjs.cmd||[];window.epbjs.cmd.push(function(){var storageType="cookie";if(typeof _ezaq!=="undefined"&&_ezaq.hasOwnProperty("prebid_reduce_cookies")&&_ezaq.prebid_reduce_cookies===true){storageType="html5";}
let uidConfig={name:"liveIntentId",params:{distributorId:"did-006t",requestedAttributesOverrides:{uid2:true,bidswitch:true,medianet:true,magnite:true,pubmatic:true,index:true,openx:true,thetradedesk:true,sovrn:true,vidazoo:true,sonobi:true,sharethrough:true,triplelift:true,nexxen:true,zetassp:true,},userAgent:navigator.userAgent,},storage:{type:storageType,name:"pbjs_li_nonid",expires:1,},};if(window._ezaq?.ipv4){uidConfig.params.ipv4=window._ezaq.ipv4;}
if(window._ezaq?.ipv6){uidConfig.params.ipv6=window._ezaq.ipv6;}
if(window.ezoicIdentity?.getUID){let ezId=window.ezoicIdentity.getUID();if(ezId&&ezId?.email?.sha256){uidConfig.params.emailHash=ezId.email.sha256;}else if(ezId&&ezId?.email?.sha1){uidConfig.params.emailHash=ezId.email.sha1;}else if(ezId&&ezId?.email?.md5){uidConfig.params.emailHash=ezId.email.md5;}}
let currentConfig=epbjs.getConfig('userSync');if(currentConfig&&currentConfig.userIds){let updatedConfig={...currentConfig};updatedConfig.userIds.push(uidConfig);epbjs.setConfig({userSync:updatedConfig});epbjs.refreshUserIds({submoduleNames:["liveIntentId"]})}});},waitForCondition:function(maxWaitTimeMS,intervalTimeMS,condition){return new Promise(function(resolve,reject){if(condition()){resolve();return;}
var startTime=Date.now();var interval=setInterval(function(){if(condition()){clearInterval(interval);resolve();}else if(Date.now()>startTime+maxWaitTimeMS+1){clearInterval(interval);reject("Timeout");}},intervalTimeMS);});},sendCustomPageviewEvent:function(key,value){this.waitForCondition(5000,50,function(){return(typeof window._ezaq!=="undefined"&&typeof window._ezaq.page_view_id!=="undefined"&&typeof window.__ez!=="undefined"&&typeof window.__ez.ce!=="undefined"&&typeof window.__ez.ce.AddPageviewEvent==="function");}).then(function(){if(!window.__ez||!window.__ez.ce||typeof window.__ez.ce.AddPageviewEvent!=="function"){return;}
window.__ez.ce.AddPageviewEvent(key,value);}).catch(function(){console.error("pageview id not found or __ez.ce.AddPageviewEvent not defined");});},getIdentityBridgingExperimentBucket:function(uuid,country){const urlParams=new URLSearchParams(window.location.search);const forceBucket=urlParams.get('force_identity_bridging');if(forceBucket){const validBuckets=['liveintent','optable','optable-retention','retention','control'];if(validBuckets.includes(forceBucket)){return forceBucket;}}
if(typeof uuid!=='string'||uuid.length===0){console.warn("Invalid UUID for bucketing",uuid);return "control";}
let hash=0;for(let i=0;i<uuid.length;i++){hash=(hash<<5)-hash+uuid.charCodeAt(i);hash|=0;}
const u=hash>>>0;const x=u/2**32;if(x<0.10)return "control";if(country!=="US")return "control";if(x<0.20)return "liveintent";if(x<0.60)return "optable";if(x<0.80)return "optable-retention";return "retention";},});var ezLiveIntentQueuedFunc=function(){};window.__ezLiveIntent.cmd=window.__ezLiveIntent.cmd||[];if(window.__ezLiveIntent.cmd.length>0){ezLiveIntentQueuedFunc=function(){for(var i=0;i<window.__ezLiveIntent.cmd.length;i++){if(typeof window.__ezLiveIntent.cmd[i]==='function'){window.__ezLiveIntent.cmd[i]();}}}}
window.__ezLiveIntent.cmd.push=function(func){if(typeof func==='function'){func();}};window.__ezLiveIntent.waitForCondition(5000,50,function(){return(typeof window._ezaq!=="undefined"&&typeof window._ezaq.visit_uuid!=="undefined");}).then(function(){window.__ezLiveIntent.init();}).catch(function(){console.error("visit_uuid not found for __ezLiveIntent.init to be called");});