extends SceneTree

# Dump the tutorial prompt-token vocabulary to JSON so the offline voiceover
# generator (tools/generate_tutorial_vo.py) can speak the SAME button and key
# names the on-screen card shows.
#
#     godot --headless --path 40k --script res://tools/dump_vo_tokens.gd
#
# Writes res://data/tutorials/vo_tokens.json. The file is committed so the
# generator runs without Godot; re-run this whenever a default keybinding or a
# glyph label changes.
#
# Autoloads are NOT up during _init() (the probe prints a freed object), so the
# work happens on the first process frame instead.

const GlyphDB := preload("res://scripts/input/GlyphDB.gd")
const LESSON_DIR := "res://data/tutorials/lessons"
const OUT_PATH := "res://data/tutorials/vo_tokens.json"

var _done := false


func _process(_delta: float) -> bool:
	if _done:
		return true
	_done = true

	var keys := {}
	var glyphs := {}
	var kbm := root.get_node_or_null("KeybindingManager")
	var unresolved: Array = []

	for entry in _tokens_used():
		var token := str(entry)
		if token.begins_with("key:"):
			var action := token.substr(4)
			if kbm == null:
				unresolved.append(token)
			else:
				var key_name: String = kbm.get_key_display_name(action)
				if key_name == "???":
					unresolved.append(token)
				else:
					keys[action] = key_name
		else:
			glyphs[token] = GlyphDB.glyph_text(token)

	if not unresolved.is_empty():
		push_error("dump_vo_tokens: unresolved tokens %s" % str(unresolved))
		print("VO_TOKENS_ERROR unresolved=%s" % str(unresolved))
		return true

	var payload := {
		"_comment": "Generated by tools/dump_vo_tokens.gd — do not hand-edit.",
		"keys": keys,
		"glyphs": glyphs,
	}
	var f := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if f == null:
		print("VO_TOKENS_ERROR cannot write %s" % OUT_PATH)
		return true
	f.store_string(JSON.stringify(payload, "  ", true) + "\n")
	f.close()
	print("VO_TOKENS_OK keys=%d glyphs=%d -> %s" % [keys.size(), glyphs.size(), OUT_PATH])
	return true


# Every distinct {token} appearing anywhere in the lesson files, so the dump
# covers exactly what the generator has to speak (and nothing it does not).
func _tokens_used() -> Array:
	var found := {}
	var re := RegEx.new()
	re.compile("\\{([a-zA-Z0-9_]+?)(?::([a-zA-Z0-9_]+))?\\}")
	var dir := DirAccess.open(LESSON_DIR)
	if dir == null:
		return []
	for file in dir.get_files():
		if not file.ends_with(".json"):
			continue
		var f := FileAccess.open("%s/%s" % [LESSON_DIR, file], FileAccess.READ)
		if f == null:
			continue
		for m in re.search_all(f.get_as_text()):
			var kind := m.get_string(1)
			var arg := m.get_string(2)
			if arg == "":
				found[kind] = true
			else:
				found["%s:%s" % [kind, arg]] = true
	var out := found.keys()
	out.sort()
	return out
